name: student-collection-manager-server
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - sgm-rabbitmq_data:/var/lib/rabbitmq

  postgres:
    image: postgres
    container_name: postgres-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - sgm-postgres:/var/lib/postgresql/data

volumes:
  sgm-rabbitmq_data:
  sgm-pgadmin-volume:
  sgm-postgres: